#if UNITY_5_3_OR_NEWER && UNITY_EDITOR
using System;
using System.Text;

namespace PBBox.SourceGenerate
{
    internal static partial class CodeGenerator
    {
        private static void BeginGenericContent(StringBuilder sb, string className, string[] extralUsings = null, bool isStatic = true, bool isPartial = true, string nameSpace = null)
        {
            if (nameSpace == null)
            {
                nameSpace = "PBBox.Generated";
            }
            sb.AppendLine("//<auto-generated>");
            sb.AppendLine("//This code is generated by PBBox.SourceGenerate.CodeGenerator, do not modify it manually.");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using PBBox;");
            if (extralUsings != null)
            {
                foreach (var u in extralUsings)
                {
                    sb.AppendLine($"using {u};");
                }
            }
            sb.AppendLine();
            sb.AppendLine($"namespace {nameSpace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static partial class {className}");
            sb.AppendLine("    {");
        }
        
        private static void EndGenericContent(StringBuilder sb)
        {
            sb.AppendLine("    }");
            sb.AppendLine("}");
        }

        [RegisterGenerator]
        private static CodeItem[] _GenPBBoxRegister()
        {
            StringBuilder sb = new StringBuilder();
            BeginGenericContent(sb, "PBBoxRegister");
            //Contents
            string content = @"
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]
        private static void RegisterAfterAssembliesLoaded()
        {
            RegisterSingletons();
        }

        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
        private static void RegisterBeforeSceneLoad()
        {
            RegisterViewControllers();
        }

        static partial void RegisterSingletons();
        static partial void RegisterViewControllers();
        ";
            sb.AppendLine(content);
            EndGenericContent(sb);
            return new CodeItem[]
            {
                new CodeItem("PBBoxRegister.g.cs", sb.ToString())
            };
        }
    }
}
#endif