#if UNITY_5_3_OR_NEWER && UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Runtime.CompilerServices;

namespace PBBox.SourceGenerate
{
    internal static partial class CodeGenerator
    {
        private const string CodePath = "Scripts/PBBox/AutoGenerated/";

        /// <summary>
        /// 代码生成入口，使用原生成器前的中间方案，先在Assets中手动生成显式代码
        /// </summary>
        [UnityEditor.MenuItem("Tools/PBBox/Generate Code", priority = 9999)]
        internal static void StartGenerate()
        {
            var codeItems = new List<CodeItem>();
            foreach (var method in typeof(CodeGenerator).GetMethods(System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic))
            {
                if (method.GetCustomAttributes(typeof(RegisterGeneratorAttribute), false).Length > 0)
                {
                    var result = method.Invoke(null, null) as CodeItem[];
                    if (result != null)
                    {
                        codeItems.AddRange(result);
                    }
                }
            }

            var rootPath = Path.Combine(UnityEngine.Application.dataPath, CodePath);

            foreach (var item in codeItems)
            {
                var filePath = Path.Combine(rootPath, item.fileName);
                var dirPath = Path.GetDirectoryName(filePath);
                if (!Directory.Exists(dirPath))
                {
                    Directory.CreateDirectory(dirPath);
                }
                File.WriteAllText(filePath, item.content);
            }

            UnityEditor.AssetDatabase.Refresh();
        }

        [UnityEditor.MenuItem("Tools/PBBox/Clear Generated Code", priority = 10000)]
        internal static void ClearGenerated()
        {
            var rootPath = Path.Combine(UnityEngine.Application.dataPath, CodePath);
            if (Directory.Exists(rootPath))
            {
                Directory.Delete(rootPath, true);
            }
            UnityEditor.AssetDatabase.Refresh();
        }

        #region Utils
        /// <summary>
        /// 获得类型对于targetAssembly是否可见
        /// </summary>
        /// <param name="type"></param>
        /// <param name="targetAssemblyName"></param>
        /// <returns></returns>
        public static bool IsTypeAccessibleFromAssembly(this Type type, string targetAssemblyName)
        {
            // 沿 DeclaringType 链逐层检查，每一层都要可访问
            for (Type t = type; t != null; t = t.DeclaringType)
            {
                if (!IsSingleTypeAccessibleFromAssembly(t, targetAssemblyName))
                    return false;
            }
            return true;
        }

        private static bool IsSingleTypeAccessibleFromAssembly(Type type, string targetAssemblyName)
        {
            if (!type.IsNested)
            {
                // 顶层类型
                if (type.IsPublic)
                    return true;                       // public：对外部任何程序集可见

                if (type.IsNotPublic)                  // internal
                    return IsSameOrFriendly(type.Assembly, targetAssemblyName);

                return false;
            }

            // 嵌套类型
            if (type.IsNestedPublic)
                return true;                           // nested public

            if (type.IsNestedAssembly)                 // nested internal
                return IsSameOrFriendly(type.Assembly, targetAssemblyName);

            if (type.IsNestedFamORAssem)               // protected internal
                return IsSameOrFriendly(type.Assembly, targetAssemblyName);

            // private / protected / private protected：
            // 代码生成视角下视为不可访问
            return false;
        }

        private static bool IsSameOrFriendly(Assembly definingAssembly, string targetAssemblyName)
        {
            string definingName = definingAssembly.GetName().Name;

            // 1. 类型所在程序集就是目标程序集
            if (string.Equals(definingName, targetAssemblyName, StringComparison.OrdinalIgnoreCase))
                return true;

            // 2. 检查 InternalsVisibleTo
            var attrs = definingAssembly.GetCustomAttributes(typeof(InternalsVisibleToAttribute), false);
            foreach (InternalsVisibleToAttribute attr in attrs)
            {
                // attr.AssemblyName 可能是完整名称（含版本/公钥），用 AssemblyName 解析出简单名称
                var an = new AssemblyName(attr.AssemblyName);
                if (string.Equals(an.Name, targetAssemblyName, StringComparison.OrdinalIgnoreCase))
                    return true;
            }

            return false;
        }

        /// <summary>
        /// 获得类型的代码访问路径
        /// </summary>
        /// <param name="type"></param>
        /// <returns></returns>
        public static string GetAccessPath(this Type type)
        {
            if (type.IsNested)
            {
                // 嵌套类型：外层路径 + "." + 自己的名字
                return GetAccessPath(type.DeclaringType) + "." + type.Name;
            }

            // 非嵌套类型：命名空间 + 名字
            if (string.IsNullOrEmpty(type.Namespace))
                return type.Name;

            return type.Namespace + "." + type.Name;
        }
        #endregion

        internal struct CodeItem
        {
            public readonly string fileName;
            public readonly string content;

            public CodeItem(string fileName, string content)
            {
                this.fileName = fileName;
                this.content = content;
            }
        }

    }
}
#endif